# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Loc Q Trinh'
tagline:          'USC Ph.D.'
description:      'CS Ph.D. student at USC | Causal Inference, Interpretability, and Healthcare | Previously MIT CSAIL, Yelp | <a href="https://twitter.com/lqtrinhz" target="_blank">@lqtrinhz</a>'
url:              https://lqtrinh.com
baseurl:          /

author:
  name:           'Loc Q Trinh'
  url:            https://twitter.com/lqtrinhz

paginate:         5
paginate_path: "/blog/page:num/"

# Custom vars
version:          4.1.1

github:
  repo:           https://github.com/poole/hyde

plugins: [jekyll-paginate, jekyll-gist]
gist:
  noscript: false