# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
relative_permalinks: false
permalink: /:title


# Setup
title:            'Loc Q Trinh'
tagline:          'USC Ph.D.'
description:      'CS Ph.D. student at USC | Causal Inference, Interpretability, and Healthcare | Previously MIT CSAIL, Yelp | <a href="https://twitter.com/lqtrinhz" target="_blank">@lqtrinhz</a>'
url:              https://lqtrinh.com
baseurl:          /

author:
  name:           'Loc Q Trinh'
  url:            https://twitter.com/lqtrinhz

# Custom vars
version:          4.1.1

github:
  repo:           https://github.com/loc-trinh/loc-trinh.github.io

plugins: [jekyll-gist]
gist:
  noscript: false

prod-analytics-id:  UA-173934346-1
dev-analytics-id:   UA-173934346-2